/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clove API
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppCreateAppInput,
  AppCreateAppOutput,
  AppKeysListAppApiKeysParams,
  AuthMeOutput,
  AuthSignInInput,
  AuthSignupInput,
  AuthSignupOutput,
  GeneratedRepoApp,
  KeysCreateKeyInput,
  KeysCreateKeyOutput,
  KeysListKeysOutput,
  RegionsListRegionsOutput,
  RegionsUpdateRegionsInput,
  RegionsUpdateRegionsOutput,
  RestErrResponse,
  TokensCreateTokenInput,
  TokensCreateTokenOutput,
  UuidUUID
} from './generated.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary List Apps
 */
export type v1AppListAppsResponse200 = {
  data: GeneratedRepoApp[] | null
  status: 200
}

export type v1AppListAppsResponseSuccess = (v1AppListAppsResponse200) & {
  headers: Headers;
};
;

export type v1AppListAppsResponse = (v1AppListAppsResponseSuccess)

export const getV1AppListAppsUrl = () => {




  return `/api/v1/apps`
}

export const v1AppListApps = async (options?: RequestInit): Promise<v1AppListAppsResponse> => {

  const res = await fetch(getV1AppListAppsUrl(),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: v1AppListAppsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as v1AppListAppsResponse
}





export const getV1AppListAppsQueryKey = () => {
  return [
    `/api/v1/apps`
  ] as const;
}


export const getV1AppListAppsQueryOptions = <TData = Awaited<ReturnType<typeof v1AppListApps>>, TError = unknown>(options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof v1AppListApps>>, TError, TData>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getV1AppListAppsQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof v1AppListApps>>> = ({ signal }) => v1AppListApps({ signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof v1AppListApps>>, TError, TData> & { queryKey: QueryKey }
}

export type V1AppListAppsQueryResult = NonNullable<Awaited<ReturnType<typeof v1AppListApps>>>
export type V1AppListAppsQueryError = unknown


/**
 * @summary List Apps
 */

export function useV1AppListApps<TData = Awaited<ReturnType<typeof v1AppListApps>>, TError = unknown>(
  options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof v1AppListApps>>, TError, TData>, fetch?: RequestInit }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getV1AppListAppsQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Create App
 */
export type v1AppCreateAppResponse200 = {
  data: AppCreateAppOutput
  status: 200
}

export type v1AppCreateAppResponse400 = {
  data: RestErrResponse
  status: 400
}

export type v1AppCreateAppResponse401 = {
  data: RestErrResponse
  status: 401
}

export type v1AppCreateAppResponse500 = {
  data: RestErrResponse
  status: 500
}

export type v1AppCreateAppResponseSuccess = (v1AppCreateAppResponse200) & {
  headers: Headers;
};
export type v1AppCreateAppResponseError = (v1AppCreateAppResponse400 | v1AppCreateAppResponse401 | v1AppCreateAppResponse500) & {
  headers: Headers;
};

export type v1AppCreateAppResponse = (v1AppCreateAppResponseSuccess | v1AppCreateAppResponseError)

export const getV1AppCreateAppUrl = () => {




  return `/api/v1/apps`
}

export const v1AppCreateApp = async (appCreateAppInput: AppCreateAppInput, options?: RequestInit): Promise<v1AppCreateAppResponse> => {

  const res = await fetch(getV1AppCreateAppUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        appCreateAppInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: v1AppCreateAppResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as v1AppCreateAppResponse
}




export const getV1AppCreateAppMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AppCreateApp>>, TError, { data: AppCreateAppInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof v1AppCreateApp>>, TError, { data: AppCreateAppInput }, TContext> => {

  const mutationKey = ['v1AppCreateApp'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof v1AppCreateApp>>, { data: AppCreateAppInput }> = (props) => {
    const { data } = props ?? {};

    return v1AppCreateApp(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type V1AppCreateAppMutationResult = NonNullable<Awaited<ReturnType<typeof v1AppCreateApp>>>
export type V1AppCreateAppMutationBody = AppCreateAppInput
export type V1AppCreateAppMutationError = RestErrResponse

/**
* @summary Create App
*/
export const useV1AppCreateApp = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AppCreateApp>>, TError, { data: AppCreateAppInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof v1AppCreateApp>>,
    TError,
    { data: AppCreateAppInput },
    TContext
  > => {
  return useMutation(getV1AppCreateAppMutationOptions(options));
}

/**
 * @summary List API Keys
 */
export type appKeysListAppApiKeysResponse200 = {
  data: KeysListKeysOutput
  status: 200
}

export type appKeysListAppApiKeysResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appKeysListAppApiKeysResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appKeysListAppApiKeysResponseSuccess = (appKeysListAppApiKeysResponse200) & {
  headers: Headers;
};
export type appKeysListAppApiKeysResponseError = (appKeysListAppApiKeysResponse401 | appKeysListAppApiKeysResponse500) & {
  headers: Headers;
};

export type appKeysListAppApiKeysResponse = (appKeysListAppApiKeysResponseSuccess | appKeysListAppApiKeysResponseError)

export const getAppKeysListAppApiKeysUrl = (appId: UuidUUID,
  params?: AppKeysListAppApiKeysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/apps/${appId}/keys?${stringifiedParams}` : `/api/v1/apps/${appId}/keys`
}

export const appKeysListAppApiKeys = async (appId: UuidUUID,
  params?: AppKeysListAppApiKeysParams, options?: RequestInit): Promise<appKeysListAppApiKeysResponse> => {

  const res = await fetch(getAppKeysListAppApiKeysUrl(appId, params),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appKeysListAppApiKeysResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appKeysListAppApiKeysResponse
}





export const getAppKeysListAppApiKeysQueryKey = (appId: UuidUUID,
  params?: AppKeysListAppApiKeysParams,) => {
  return [
    `/api/v1/apps/${appId}/keys`, ...(params ? [params] : [])
  ] as const;
}


export const getAppKeysListAppApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof appKeysListAppApiKeys>>, TError = RestErrResponse>(appId: UuidUUID,
  params?: AppKeysListAppApiKeysParams, options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof appKeysListAppApiKeys>>, TError, TData>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppKeysListAppApiKeysQueryKey(appId, params);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof appKeysListAppApiKeys>>> = ({ signal }) => appKeysListAppApiKeys(appId, params, { signal, ...fetchOptions });





  return { queryKey, queryFn, enabled: !!(appId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof appKeysListAppApiKeys>>, TError, TData> & { queryKey: QueryKey }
}

export type AppKeysListAppApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof appKeysListAppApiKeys>>>
export type AppKeysListAppApiKeysQueryError = RestErrResponse


/**
 * @summary List API Keys
 */

export function useAppKeysListAppApiKeys<TData = Awaited<ReturnType<typeof appKeysListAppApiKeys>>, TError = RestErrResponse>(
  appId: UuidUUID,
  params?: AppKeysListAppApiKeysParams, options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof appKeysListAppApiKeys>>, TError, TData>, fetch?: RequestInit }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppKeysListAppApiKeysQueryOptions(appId, params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Create API Key
 */
export type appKeysCreateAppApiKeyResponse200 = {
  data: KeysCreateKeyOutput
  status: 200
}

export type appKeysCreateAppApiKeyResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appKeysCreateAppApiKeyResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appKeysCreateAppApiKeyResponseSuccess = (appKeysCreateAppApiKeyResponse200) & {
  headers: Headers;
};
export type appKeysCreateAppApiKeyResponseError = (appKeysCreateAppApiKeyResponse401 | appKeysCreateAppApiKeyResponse500) & {
  headers: Headers;
};

export type appKeysCreateAppApiKeyResponse = (appKeysCreateAppApiKeyResponseSuccess | appKeysCreateAppApiKeyResponseError)

export const getAppKeysCreateAppApiKeyUrl = (appId: UuidUUID,) => {




  return `/api/v1/apps/${appId}/keys`
}

export const appKeysCreateAppApiKey = async (appId: UuidUUID,
  keysCreateKeyInput: KeysCreateKeyInput, options?: RequestInit): Promise<appKeysCreateAppApiKeyResponse> => {

  const res = await fetch(getAppKeysCreateAppApiKeyUrl(appId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        keysCreateKeyInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appKeysCreateAppApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appKeysCreateAppApiKeyResponse
}




export const getAppKeysCreateAppApiKeyMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appKeysCreateAppApiKey>>, TError, { appId: UuidUUID; data: KeysCreateKeyInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof appKeysCreateAppApiKey>>, TError, { appId: UuidUUID; data: KeysCreateKeyInput }, TContext> => {

  const mutationKey = ['appKeysCreateAppApiKey'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof appKeysCreateAppApiKey>>, { appId: UuidUUID; data: KeysCreateKeyInput }> = (props) => {
    const { appId, data } = props ?? {};

    return appKeysCreateAppApiKey(appId, data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type AppKeysCreateAppApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof appKeysCreateAppApiKey>>>
export type AppKeysCreateAppApiKeyMutationBody = KeysCreateKeyInput
export type AppKeysCreateAppApiKeyMutationError = RestErrResponse

/**
* @summary Create API Key
*/
export const useAppKeysCreateAppApiKey = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appKeysCreateAppApiKey>>, TError, { appId: UuidUUID; data: KeysCreateKeyInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof appKeysCreateAppApiKey>>,
    TError,
    { appId: UuidUUID; data: KeysCreateKeyInput },
    TContext
  > => {
  return useMutation(getAppKeysCreateAppApiKeyMutationOptions(options));
}

/**
 * @summary Delete API Key
 */
export type appKeysDeleteAppApiKeyResponse204 = {
  data: void
  status: 204
}

export type appKeysDeleteAppApiKeyResponse400 = {
  data: RestErrResponse
  status: 400
}

export type appKeysDeleteAppApiKeyResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appKeysDeleteAppApiKeyResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appKeysDeleteAppApiKeyResponseSuccess = (appKeysDeleteAppApiKeyResponse204) & {
  headers: Headers;
};
export type appKeysDeleteAppApiKeyResponseError = (appKeysDeleteAppApiKeyResponse400 | appKeysDeleteAppApiKeyResponse401 | appKeysDeleteAppApiKeyResponse500) & {
  headers: Headers;
};

export type appKeysDeleteAppApiKeyResponse = (appKeysDeleteAppApiKeyResponseSuccess | appKeysDeleteAppApiKeyResponseError)

export const getAppKeysDeleteAppApiKeyUrl = (appId: UuidUUID,
  keyId: UuidUUID,) => {




  return `/api/v1/apps/${appId}/keys/${keyId}`
}

export const appKeysDeleteAppApiKey = async (appId: UuidUUID,
  keyId: UuidUUID, options?: RequestInit): Promise<appKeysDeleteAppApiKeyResponse> => {

  const res = await fetch(getAppKeysDeleteAppApiKeyUrl(appId, keyId),
    {
      ...options,
      method: 'DELETE'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appKeysDeleteAppApiKeyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appKeysDeleteAppApiKeyResponse
}




export const getAppKeysDeleteAppApiKeyMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>, TError, { appId: UuidUUID; keyId: UuidUUID }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>, TError, { appId: UuidUUID; keyId: UuidUUID }, TContext> => {

  const mutationKey = ['appKeysDeleteAppApiKey'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>, { appId: UuidUUID; keyId: UuidUUID }> = (props) => {
    const { appId, keyId } = props ?? {};

    return appKeysDeleteAppApiKey(appId, keyId, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type AppKeysDeleteAppApiKeyMutationResult = NonNullable<Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>>

export type AppKeysDeleteAppApiKeyMutationError = RestErrResponse

/**
* @summary Delete API Key
*/
export const useAppKeysDeleteAppApiKey = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>, TError, { appId: UuidUUID; keyId: UuidUUID }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof appKeysDeleteAppApiKey>>,
    TError,
    { appId: UuidUUID; keyId: UuidUUID },
    TContext
  > => {
  return useMutation(getAppKeysDeleteAppApiKeyMutationOptions(options));
}

/**
 * @summary List App Regions
 */
export type appRegionsListAppRegionsResponse200 = {
  data: RegionsListRegionsOutput
  status: 200
}

export type appRegionsListAppRegionsResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appRegionsListAppRegionsResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appRegionsListAppRegionsResponseSuccess = (appRegionsListAppRegionsResponse200) & {
  headers: Headers;
};
export type appRegionsListAppRegionsResponseError = (appRegionsListAppRegionsResponse401 | appRegionsListAppRegionsResponse500) & {
  headers: Headers;
};

export type appRegionsListAppRegionsResponse = (appRegionsListAppRegionsResponseSuccess | appRegionsListAppRegionsResponseError)

export const getAppRegionsListAppRegionsUrl = (appId: UuidUUID,) => {




  return `/api/v1/apps/${appId}/regions`
}

export const appRegionsListAppRegions = async (appId: UuidUUID, options?: RequestInit): Promise<appRegionsListAppRegionsResponse> => {

  const res = await fetch(getAppRegionsListAppRegionsUrl(appId),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appRegionsListAppRegionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appRegionsListAppRegionsResponse
}





export const getAppRegionsListAppRegionsQueryKey = (appId: UuidUUID,) => {
  return [
    `/api/v1/apps/${appId}/regions`
  ] as const;
}


export const getAppRegionsListAppRegionsQueryOptions = <TData = Awaited<ReturnType<typeof appRegionsListAppRegions>>, TError = RestErrResponse>(appId: UuidUUID, options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof appRegionsListAppRegions>>, TError, TData>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppRegionsListAppRegionsQueryKey(appId);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof appRegionsListAppRegions>>> = ({ signal }) => appRegionsListAppRegions(appId, { signal, ...fetchOptions });





  return { queryKey, queryFn, enabled: !!(appId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof appRegionsListAppRegions>>, TError, TData> & { queryKey: QueryKey }
}

export type AppRegionsListAppRegionsQueryResult = NonNullable<Awaited<ReturnType<typeof appRegionsListAppRegions>>>
export type AppRegionsListAppRegionsQueryError = RestErrResponse


/**
 * @summary List App Regions
 */

export function useAppRegionsListAppRegions<TData = Awaited<ReturnType<typeof appRegionsListAppRegions>>, TError = RestErrResponse>(
  appId: UuidUUID, options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof appRegionsListAppRegions>>, TError, TData>, fetch?: RequestInit }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppRegionsListAppRegionsQueryOptions(appId, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Update App Regions
 */
export type appRegionsUpdateAppRegionsResponse200 = {
  data: RegionsUpdateRegionsOutput
  status: 200
}

export type appRegionsUpdateAppRegionsResponse400 = {
  data: RestErrResponse
  status: 400
}

export type appRegionsUpdateAppRegionsResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appRegionsUpdateAppRegionsResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appRegionsUpdateAppRegionsResponseSuccess = (appRegionsUpdateAppRegionsResponse200) & {
  headers: Headers;
};
export type appRegionsUpdateAppRegionsResponseError = (appRegionsUpdateAppRegionsResponse400 | appRegionsUpdateAppRegionsResponse401 | appRegionsUpdateAppRegionsResponse500) & {
  headers: Headers;
};

export type appRegionsUpdateAppRegionsResponse = (appRegionsUpdateAppRegionsResponseSuccess | appRegionsUpdateAppRegionsResponseError)

export const getAppRegionsUpdateAppRegionsUrl = (appId: UuidUUID,) => {




  return `/api/v1/apps/${appId}/regions`
}

export const appRegionsUpdateAppRegions = async (appId: UuidUUID,
  regionsUpdateRegionsInput: RegionsUpdateRegionsInput, options?: RequestInit): Promise<appRegionsUpdateAppRegionsResponse> => {

  const res = await fetch(getAppRegionsUpdateAppRegionsUrl(appId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        regionsUpdateRegionsInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appRegionsUpdateAppRegionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appRegionsUpdateAppRegionsResponse
}




export const getAppRegionsUpdateAppRegionsMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>, TError, { appId: UuidUUID; data: RegionsUpdateRegionsInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>, TError, { appId: UuidUUID; data: RegionsUpdateRegionsInput }, TContext> => {

  const mutationKey = ['appRegionsUpdateAppRegions'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>, { appId: UuidUUID; data: RegionsUpdateRegionsInput }> = (props) => {
    const { appId, data } = props ?? {};

    return appRegionsUpdateAppRegions(appId, data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type AppRegionsUpdateAppRegionsMutationResult = NonNullable<Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>>
export type AppRegionsUpdateAppRegionsMutationBody = RegionsUpdateRegionsInput
export type AppRegionsUpdateAppRegionsMutationError = RestErrResponse

/**
* @summary Update App Regions
*/
export const useAppRegionsUpdateAppRegions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>, TError, { appId: UuidUUID; data: RegionsUpdateRegionsInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof appRegionsUpdateAppRegions>>,
    TError,
    { appId: UuidUUID; data: RegionsUpdateRegionsInput },
    TContext
  > => {
  return useMutation(getAppRegionsUpdateAppRegionsMutationOptions(options));
}

/**
 * @summary Create One-Time Token
 */
export type appTokensCreateAppOneTimeTokenResponse200 = {
  data: TokensCreateTokenOutput
  status: 200
}

export type appTokensCreateAppOneTimeTokenResponse401 = {
  data: RestErrResponse
  status: 401
}

export type appTokensCreateAppOneTimeTokenResponse404 = {
  data: RestErrResponse
  status: 404
}

export type appTokensCreateAppOneTimeTokenResponse500 = {
  data: RestErrResponse
  status: 500
}

export type appTokensCreateAppOneTimeTokenResponseSuccess = (appTokensCreateAppOneTimeTokenResponse200) & {
  headers: Headers;
};
export type appTokensCreateAppOneTimeTokenResponseError = (appTokensCreateAppOneTimeTokenResponse401 | appTokensCreateAppOneTimeTokenResponse404 | appTokensCreateAppOneTimeTokenResponse500) & {
  headers: Headers;
};

export type appTokensCreateAppOneTimeTokenResponse = (appTokensCreateAppOneTimeTokenResponseSuccess | appTokensCreateAppOneTimeTokenResponseError)

export const getAppTokensCreateAppOneTimeTokenUrl = (appId: UuidUUID,) => {




  return `/api/v1/apps/${appId}/tokens`
}

export const appTokensCreateAppOneTimeToken = async (appId: UuidUUID,
  tokensCreateTokenInput: TokensCreateTokenInput, options?: RequestInit): Promise<appTokensCreateAppOneTimeTokenResponse> => {

  const res = await fetch(getAppTokensCreateAppOneTimeTokenUrl(appId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        tokensCreateTokenInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appTokensCreateAppOneTimeTokenResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appTokensCreateAppOneTimeTokenResponse
}




export const getAppTokensCreateAppOneTimeTokenMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>, TError, { appId: UuidUUID; data: TokensCreateTokenInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>, TError, { appId: UuidUUID; data: TokensCreateTokenInput }, TContext> => {

  const mutationKey = ['appTokensCreateAppOneTimeToken'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>, { appId: UuidUUID; data: TokensCreateTokenInput }> = (props) => {
    const { appId, data } = props ?? {};

    return appTokensCreateAppOneTimeToken(appId, data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type AppTokensCreateAppOneTimeTokenMutationResult = NonNullable<Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>>
export type AppTokensCreateAppOneTimeTokenMutationBody = TokensCreateTokenInput
export type AppTokensCreateAppOneTimeTokenMutationError = RestErrResponse

/**
* @summary Create One-Time Token
*/
export const useAppTokensCreateAppOneTimeToken = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>, TError, { appId: UuidUUID; data: TokensCreateTokenInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof appTokensCreateAppOneTimeToken>>,
    TError,
    { appId: UuidUUID; data: TokensCreateTokenInput },
    TContext
  > => {
  return useMutation(getAppTokensCreateAppOneTimeTokenMutationOptions(options));
}

/**
 * @summary Get Current User
 */
export type v1AuthMeResponse200 = {
  data: AuthMeOutput
  status: 200
}

export type v1AuthMeResponse401 = {
  data: RestErrResponse
  status: 401
}

export type v1AuthMeResponseSuccess = (v1AuthMeResponse200) & {
  headers: Headers;
};
export type v1AuthMeResponseError = (v1AuthMeResponse401) & {
  headers: Headers;
};

export type v1AuthMeResponse = (v1AuthMeResponseSuccess | v1AuthMeResponseError)

export const getV1AuthMeUrl = () => {




  return `/api/v1/auth/me`
}

export const v1AuthMe = async (options?: RequestInit): Promise<v1AuthMeResponse> => {

  const res = await fetch(getV1AuthMeUrl(),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: v1AuthMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as v1AuthMeResponse
}





export const getV1AuthMeQueryKey = () => {
  return [
    `/api/v1/auth/me`
  ] as const;
}


export const getV1AuthMeQueryOptions = <TData = Awaited<ReturnType<typeof v1AuthMe>>, TError = RestErrResponse>(options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof v1AuthMe>>, TError, TData>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getV1AuthMeQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof v1AuthMe>>> = ({ signal }) => v1AuthMe({ signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof v1AuthMe>>, TError, TData> & { queryKey: QueryKey }
}

export type V1AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof v1AuthMe>>>
export type V1AuthMeQueryError = RestErrResponse


/**
 * @summary Get Current User
 */

export function useV1AuthMe<TData = Awaited<ReturnType<typeof v1AuthMe>>, TError = RestErrResponse>(
  options?: { query?: UseQueryOptions<Awaited<ReturnType<typeof v1AuthMe>>, TError, TData>, fetch?: RequestInit }

): UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getV1AuthMeQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary User Sign In
 */
export type v1AuthSignInResponse204 = {
  data: void
  status: 204
}

export type v1AuthSignInResponse401 = {
  data: RestErrResponse
  status: 401
}

export type v1AuthSignInResponseSuccess = (v1AuthSignInResponse204) & {
  headers: Headers;
};
export type v1AuthSignInResponseError = (v1AuthSignInResponse401) & {
  headers: Headers;
};

export type v1AuthSignInResponse = (v1AuthSignInResponseSuccess | v1AuthSignInResponseError)

export const getV1AuthSignInUrl = () => {




  return `/api/v1/auth/sign-in`
}

export const v1AuthSignIn = async (authSignInInput: AuthSignInInput, options?: RequestInit): Promise<v1AuthSignInResponse> => {

  const res = await fetch(getV1AuthSignInUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        authSignInInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: v1AuthSignInResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as v1AuthSignInResponse
}




export const getV1AuthSignInMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignIn>>, TError, { data: AuthSignInInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignIn>>, TError, { data: AuthSignInInput }, TContext> => {

  const mutationKey = ['v1AuthSignIn'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof v1AuthSignIn>>, { data: AuthSignInInput }> = (props) => {
    const { data } = props ?? {};

    return v1AuthSignIn(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type V1AuthSignInMutationResult = NonNullable<Awaited<ReturnType<typeof v1AuthSignIn>>>
export type V1AuthSignInMutationBody = AuthSignInInput
export type V1AuthSignInMutationError = RestErrResponse

/**
* @summary User Sign In
*/
export const useV1AuthSignIn = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignIn>>, TError, { data: AuthSignInInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof v1AuthSignIn>>,
    TError,
    { data: AuthSignInInput },
    TContext
  > => {
  return useMutation(getV1AuthSignInMutationOptions(options));
}

/**
 * @summary User Signup
 */
export type v1AuthSignupResponse200 = {
  data: AuthSignupOutput
  status: 200
}

export type v1AuthSignupResponse409 = {
  data: RestErrResponse
  status: 409
}

export type v1AuthSignupResponse500 = {
  data: RestErrResponse
  status: 500
}

export type v1AuthSignupResponseSuccess = (v1AuthSignupResponse200) & {
  headers: Headers;
};
export type v1AuthSignupResponseError = (v1AuthSignupResponse409 | v1AuthSignupResponse500) & {
  headers: Headers;
};

export type v1AuthSignupResponse = (v1AuthSignupResponseSuccess | v1AuthSignupResponseError)

export const getV1AuthSignupUrl = () => {




  return `/api/v1/auth/sign-up`
}

export const v1AuthSignup = async (authSignupInput: AuthSignupInput, options?: RequestInit): Promise<v1AuthSignupResponse> => {

  const res = await fetch(getV1AuthSignupUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        authSignupInput,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: v1AuthSignupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as v1AuthSignupResponse
}




export const getV1AuthSignupMutationOptions = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignup>>, TError, { data: AuthSignupInput }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignup>>, TError, { data: AuthSignupInput }, TContext> => {

  const mutationKey = ['v1AuthSignup'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof v1AuthSignup>>, { data: AuthSignupInput }> = (props) => {
    const { data } = props ?? {};

    return v1AuthSignup(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type V1AuthSignupMutationResult = NonNullable<Awaited<ReturnType<typeof v1AuthSignup>>>
export type V1AuthSignupMutationBody = AuthSignupInput
export type V1AuthSignupMutationError = RestErrResponse

/**
* @summary User Signup
*/
export const useV1AuthSignup = <TError = RestErrResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof v1AuthSignup>>, TError, { data: AuthSignupInput }, TContext>, fetch?: RequestInit }
  ): UseMutationResult<
    Awaited<ReturnType<typeof v1AuthSignup>>,
    TError,
    { data: AuthSignupInput },
    TContext
  > => {
  return useMutation(getV1AuthSignupMutationOptions(options));
}

