/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Clove API
 * OpenAPI spec version: 0.0.1
 */
export type AppCreateAppInputPlan = typeof AppCreateAppInputPlan[keyof typeof AppCreateAppInputPlan];


export const AppCreateAppInputPlan = {
  free: 'free',
  pro: 'pro',
  enterprise: 'enterprise',
} as const;

export type UuidUUID = string;

export interface AppCreateAppInput {
  /** @nullable */
  allowed_origins?: string[] | null;
  app_slug?: string;
  plan?: AppCreateAppInputPlan;
  /** @nullable */
  regions?: string[] | null;
  user_id?: UuidUUID;
}

export interface PgtypeUUID { [key: string]: unknown }

export interface AppCreateAppOutput {
  /** @nullable */
  allowed_origins?: string[] | null;
  app_slug?: string;
  app_type?: string;
  id?: PgtypeUUID;
  /** @nullable */
  region?: string[] | null;
  user_id?: PgtypeUUID;
}

export interface PgtypeTimestamp { [key: string]: unknown }

export interface GeneratedRepoNullUserRole {
  user_role?: string;
  valid?: boolean;
}

export interface AuthMeOutput {
  created_at?: PgtypeTimestamp;
  hash?: string;
  id?: PgtypeUUID;
  number_of_emails?: number;
  role?: GeneratedRepoNullUserRole;
  updated_at?: PgtypeTimestamp;
}

export interface AuthSignInInput {
  email?: string;
  password?: string;
}

export interface AuthSignupInput {
  confirm_password?: string;
  email?: string;
  password?: string;
}

export interface AuthSignupOutput {
  created_at?: PgtypeTimestamp;
  hash?: string;
  id?: PgtypeUUID;
  number_of_emails?: number;
  role?: GeneratedRepoNullUserRole;
  updated_at?: PgtypeTimestamp;
}

export interface GeneratedRepoApp {
  /** @nullable */
  allowed_origins?: string[] | null;
  app_slug?: string;
  app_type?: string;
  id?: PgtypeUUID;
  /** @nullable */
  region?: string[] | null;
  user_id?: PgtypeUUID;
}

export interface PgtypeText { [key: string]: unknown }

export interface GeneratedRepoAppApiKey {
  app_id?: PgtypeUUID;
  created_at?: PgtypeTimestamp;
  expires_at?: PgtypeTimestamp;
  id?: string;
  name?: PgtypeText;
  prefix?: PgtypeText;
  suffix?: PgtypeText;
  updated_at?: PgtypeTimestamp;
}

export interface KeysCreateKeyInput {
  name?: string;
}

export interface KeysCreateKeyOutput {
  app_id?: PgtypeUUID;
  created_at?: PgtypeTimestamp;
  expires_at?: PgtypeTimestamp;
  id?: string;
  name?: PgtypeText;
  prefix?: PgtypeText;
  suffix?: PgtypeText;
  token?: string;
  updated_at?: PgtypeTimestamp;
}

export interface KeysListKeysOutput {
  /** @nullable */
  keys?: GeneratedRepoAppApiKey[] | null;
}

export interface RegionsListRegionsOutput {
  /** @nullable */
  regions?: string[] | null;
}

export interface RegionsUpdateRegionsInput {
  /** @nullable */
  regions?: string[] | null;
}

export interface RegionsUpdateRegionsOutput {
  /** @nullable */
  regions?: string[] | null;
}

/**
 * Application context.
 */
export type RestErrResponseContext = {[key: string]: unknown};

export interface RestErrResponse {
  /** Application-specific error code. */
  code?: number;
  /** Application context. */
  context?: RestErrResponseContext;
  /** Error message. */
  error?: string;
  /** Status text. */
  status?: string;
}

export interface TokensCreateTokenInput {
  channel_id?: string;
}

export interface TokensCreateTokenOutput {
  region?: string;
  token?: string;
}

export type AppKeysListAppApiKeysParams = {
page_idx?: number;
};

