// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add-region-from-app.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRegionToApp = `-- name: AddRegionToApp :one
UPDATE "app"
SET "region" = $1
WHERE "id" = $2
RETURNING "region"
`

type AddRegionToAppParams struct {
	Region []Region    `json:"region"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AddRegionToApp(ctx context.Context, arg AddRegionToAppParams) ([]Region, error) {
	row := q.db.QueryRow(ctx, addRegionToApp, arg.Region, arg.ID)
	var region []Region
	err := row.Scan(&region)
	return region, err
}
