// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create-app-api-key.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppApiKey = `-- name: CreateAppApiKey :one

INSERT INTO "app_api_key"
("appId", "key", "name")
VALUES
($1, $2, $3)
RETURNING id, "appId", "createdAt", "updatedAt", key, name
`

type CreateAppApiKeyParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   pgtype.Text `json:"key"`
	Name  pgtype.Text `json:"name"`
}

// CREATE TABLE "app_api_key" (
//
//	"id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
//	"appId" UUID,
//	"createdAt" TIMESTAMP DEFAULT NOW(),
//	"updatedAt" TIMESTAMP DEFAULT NOW(),
//	CONSTRAINT "api_key_app_fk" FOREIGN KEY ("appId") REFERENCES "app"("id")
//
// );
func (q *Queries) CreateAppApiKey(ctx context.Context, arg CreateAppApiKeyParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, createAppApiKey, arg.AppID, arg.Key, arg.Name)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Name,
	)
	return i, err
}
