// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create-user.sql

package repository

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
insert into "user"
("email", "hash")
values(
    $1, $2
)
RETURNING id, email, hash, "createdAt", "updatedAt", role
`

type InsertUserParams struct {
	Email string `json:"email"`
	Hash  string `json:"hash"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
