// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create-app.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertApp = `-- name: InsertApp :one
INSERT INTO "app"
("appSlug", "region", "appType", "userId", "allowedOrigins")
values
($1, $2, $3, $4, $5)
RETURNING id, "appSlug", region, "appType", "userId", "allowedOrigins"
`

type InsertAppParams struct {
	AppSlug        string      `json:"app_slug"`
	Regions        []Region    `json:"regions"`
	AppType        AppType     `json:"app_type"`
	UserID         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) (App, error) {
	row := q.db.QueryRow(ctx, insertApp,
		arg.AppSlug,
		arg.Regions,
		arg.AppType,
		arg.UserID,
		arg.AllowedOrigins,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserId,
		&i.AllowedOrigins,
	)
	return i, err
}
