// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete-app.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApp = `-- name: DeleteApp :exec

DELETE FROM "app"
where "id" = $1
`

func (q *Queries) DeleteApp(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApp, id)
	return err
}
