// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete-api-key.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteApiKey = `-- name: DeleteApiKey :execrows
Delete from "app_api_key"
WHERE "id" = $1 and "appId" = $2
`

type DeleteApiKeyParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
