// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Delete = `-- name: App_Delete :exec
DELETE FROM "app"
where "id" = $1
`

func (q *Queries) App_Delete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, app_Delete, id)
	return err
}

const app_Key_Delete = `-- name: App_Key_Delete :execrows
Delete from "app_api_key"
WHERE "id" = $1 and "appId" = $2
`

type App_Key_DeleteParams struct {
	ID    pgtype.UUID `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) App_Key_Delete(ctx context.Context, arg App_Key_DeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, app_Key_Delete, arg.ID, arg.AppID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
