// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: does-app-has-this-region.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const doesAppHaveRegion = `-- name: DoesAppHaveRegion :one
SELECT EXISTS(
    SELECT 1 
    FROM "app"
    WHERE "id" = $1 
      AND $2 = ANY("region")
) AS has_region
`

type DoesAppHaveRegionParams struct {
	ID     pgtype.UUID `json:"id"`
	Region []Region    `json:"region"`
}

func (q *Queries) DoesAppHaveRegion(ctx context.Context, arg DoesAppHaveRegionParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesAppHaveRegion, arg.ID, arg.Region)
	var has_region bool
	err := row.Scan(&has_region)
	return has_region, err
}
