// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.update.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const user_Email_Update = `-- name: User_Email_Update :exec
UPDATE "user"
SET "email" = $1
Where "id" = $2
`

type User_Email_UpdateParams struct {
	Email  string      `json:"email"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) User_Email_Update(ctx context.Context, arg User_Email_UpdateParams) error {
	_, err := q.db.Exec(ctx, user_Email_Update, arg.Email, arg.UserID)
	return err
}
