// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find-app-by-id.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAppById = `-- name: FindAppById :one
SELECT id, "appSlug", region, "appType", "userId", "allowedOrigins" from "app"
where "id" = $1
limit 1
`

func (q *Queries) FindAppById(ctx context.Context, appID pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, findAppById, appID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserId,
		&i.AllowedOrigins,
	)
	return i, err
}
