// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get-api-key.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppApiKey = `-- name: GetAppApiKey :one
SELECT "key"
FROM "app_api_key"
WHERE "id" = $1 AND "appId" = $2
limit 1
`

type GetAppApiKeyParams struct {
	KeyID pgtype.UUID `json:"key_id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetAppApiKey(ctx context.Context, arg GetAppApiKeyParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getAppApiKey, arg.KeyID, arg.AppID)
	var key pgtype.Text
	err := row.Scan(&key)
	return key, err
}
