// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Insert = `-- name: App_Insert :one
INSERT INTO "app"
("appSlug", "region", "appType", "userId", "allowedOrigins")
values
($1, $2, $3, $4, $5)
RETURNING id, "appSlug", region, "appType", "userId", "allowedOrigins"
`

type App_InsertParams struct {
	AppSlug        string      `json:"app_slug"`
	Regions        []Region    `json:"regions"`
	AppType        AppType     `json:"app_type"`
	UserID         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

func (q *Queries) App_Insert(ctx context.Context, arg App_InsertParams) (App, error) {
	row := q.db.QueryRow(ctx, app_Insert,
		arg.AppSlug,
		arg.Regions,
		arg.AppType,
		arg.UserID,
		arg.AllowedOrigins,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserId,
		&i.AllowedOrigins,
	)
	return i, err
}

const app_Key_Insert = `-- name: App_Key_Insert :one
INSERT INTO "app_api_key"
("appId", "key", "name")
VALUES
($1, $2, $3)
RETURNING id, "appId", "createdAt", "updatedAt", key, name
`

type App_Key_InsertParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   pgtype.Text `json:"key"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) App_Key_Insert(ctx context.Context, arg App_Key_InsertParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, app_Key_Insert, arg.AppID, arg.Key, arg.Name)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppId,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Name,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
insert into "user"
("email", "hash")
values(
    $1, $2
)
RETURNING id, email, hash, "createdAt", "updatedAt", role
`

type InsertUserParams struct {
	Email string `json:"email"`
	Hash  string `json:"hash"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Email, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
