// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Insert = `-- name: App_Insert :one
INSERT INTO "app"
("app_slug", "region", "app_type", "user_id", "allowed_origins")
values
($1, $2, $3, $4, $5)
RETURNING id, app_slug, region, app_type, user_id, allowed_origins
`

type App_InsertParams struct {
	AppSlug        string      `json:"app_slug"`
	Regions        []Region    `json:"regions"`
	AppType        AppType     `json:"app_type"`
	UserID         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

func (q *Queries) App_Insert(ctx context.Context, arg App_InsertParams) (App, error) {
	row := q.db.QueryRow(ctx, app_Insert,
		arg.AppSlug,
		arg.Regions,
		arg.AppType,
		arg.UserID,
		arg.AllowedOrigins,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserID,
		&i.AllowedOrigins,
	)
	return i, err
}

const app_Key_Insert = `-- name: App_Key_Insert :one
INSERT INTO "app_api_key"
("app_id", "key", "name")
VALUES
($1, $2, $3)
RETURNING id, app_id, created_at, updated_at, key, name
`

type App_Key_InsertParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Key   pgtype.Text `json:"key"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) App_Key_Insert(ctx context.Context, arg App_Key_InsertParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, app_Key_Insert, arg.AppID, arg.Key, arg.Name)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Name,
	)
	return i, err
}

const userEmail_Insert = `-- name: UserEmail_Insert :one
INSERT INTO "user_email"
("email", "user_id", "code")
VALUES($1, $2, $3)
RETURNING id, email, user_id, created_at, updated_at, verified_at, code
`

type UserEmail_InsertParams struct {
	Email  string      `json:"email"`
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) UserEmail_Insert(ctx context.Context, arg UserEmail_InsertParams) (UserEmail, error) {
	row := q.db.QueryRow(ctx, userEmail_Insert, arg.Email, arg.UserID, arg.Code)
	var i UserEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.Code,
	)
	return i, err
}

const user_Insert = `-- name: User_Insert :one
insert into "user"("hash") values($1) RETURNING id, hash, created_at, updated_at, role, number_of_emails
`

func (q *Queries) User_Insert(ctx context.Context, hash string) (User, error) {
	row := q.db.QueryRow(ctx, user_Insert, hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.NumberOfEmails,
	)
	return i, err
}
