// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list-app-regions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAppRegions = `-- name: ListAppRegions :one
SELECT "region"
FROM "app"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) ListAppRegions(ctx context.Context, id pgtype.UUID) ([]Region, error) {
	row := q.db.QueryRow(ctx, listAppRegions, id)
	var region []Region
	err := row.Scan(&region)
	return region, err
}
