// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Key_List = `-- name: App_Key_List :many
SELECT id, "appId", "createdAt", "updatedAt", key, name from "app_api_key"
WHERE   "appId" = $1
Limit 20
OFFSET 10 *  $2::int
`

type App_Key_ListParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	PageIdx int32       `json:"page_idx"`
}

func (q *Queries) App_Key_List(ctx context.Context, arg App_Key_ListParams) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, app_Key_List, arg.AppID, arg.PageIdx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppApiKey
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AppId,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Key,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
