// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: region.select.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Region_Select = `-- name: App_Region_Select :one
SELECT "region"
FROM "app"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) App_Region_Select(ctx context.Context, id pgtype.UUID) ([]Region, error) {
	row := q.db.QueryRow(ctx, app_Region_Select, id)
	var region []Region
	err := row.Scan(&region)
	return region, err
}
