// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: region.update.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Region_Update = `-- name: App_Region_Update :exec
UPDATE "app"
SET "region" = $1
WHERE "id" = $2
RETURNING "region"
`

type App_Region_UpdateParams struct {
	Region []Region    `json:"region"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) App_Region_Update(ctx context.Context, arg App_Region_UpdateParams) error {
	_, err := q.db.Exec(ctx, app_Region_Update, arg.Region, arg.ID)
	return err
}
