// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: remove-region-from-app.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const removeRegionFromApp = `-- name: RemoveRegionFromApp :one
UPDATE "app"
SET "region" = ARRAY_REMOVE("region", $1::region)
WHERE "id" = $2
RETURNING "region"
`

type RemoveRegionFromAppParams struct {
	Region Region      `json:"region"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RemoveRegionFromApp(ctx context.Context, arg RemoveRegionFromAppParams) ([]Region, error) {
	row := q.db.QueryRow(ctx, removeRegionFromApp, arg.Region, arg.ID)
	var region []Region
	err := row.Scan(&region)
	return region, err
}
