// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Key_Select = `-- name: App_Key_Select :one
SELECT id, app_id, created_at, updated_at, key, name
FROM "app_api_key"
WHERE "id" = $1 AND "app_id" = $2
limit 1
`

type App_Key_SelectParams struct {
	KeyID pgtype.UUID `json:"key_id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) App_Key_Select(ctx context.Context, arg App_Key_SelectParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, app_Key_Select, arg.KeyID, arg.AppID)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Key,
		&i.Name,
	)
	return i, err
}

const app_Select = `-- name: App_Select :one
SELECT id, app_slug, region, app_type, user_id, allowed_origins from "app"
where "id" = $1
limit 1
`

func (q *Queries) App_Select(ctx context.Context, appID pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, app_Select, appID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserID,
		&i.AllowedOrigins,
	)
	return i, err
}
