// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update-app-regions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateAppRegions = `-- name: UpdateAppRegions :exec
UPDATE "app"
SET "region" = $1
WHERE "id" = $2
RETURNING id, "appSlug", region, "appType", "userId", "allowedOrigins"
`

type UpdateAppRegionsParams struct {
	Regions []Region    `json:"regions"`
	AppID   pgtype.UUID `json:"app_id"`
}

func (q *Queries) UpdateAppRegions(ctx context.Context, arg UpdateAppRegionsParams) error {
	_, err := q.db.Exec(ctx, updateAppRegions, arg.Regions, arg.AppID)
	return err
}
