// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userEmails_Verify = `-- name: UserEmails_Verify :exec
UPDATE "user_email"
SET
    "verified_at" = NOW()
WHERE "id" = $1
`

func (q *Queries) UserEmails_Verify(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userEmails_Verify, id)
	return err
}
