// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userEmail_Select = `-- name: UserEmail_Select :one
SELECT
    id, email, user_id, created_at, updated_at, verified_at, code
FROM "user_email"
WHERE "id" = $1
`

func (q *Queries) UserEmail_Select(ctx context.Context, userID pgtype.UUID) (UserEmail, error) {
	row := q.db.QueryRow(ctx, userEmail_Select, userID)
	var i UserEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.Code,
	)
	return i, err
}

const userEmail_SelectByEmail = `-- name: UserEmail_SelectByEmail :one
SELECT
    id, email, user_id, created_at, updated_at, verified_at, code
FROM "user_email"
WHERE "email" = $1
`

func (q *Queries) UserEmail_SelectByEmail(ctx context.Context, email string) (UserEmail, error) {
	row := q.db.QueryRow(ctx, userEmail_SelectByEmail, email)
	var i UserEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.Code,
	)
	return i, err
}
