// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Insert = `-- name: App_Insert :one
INSERT INTO "app"
("app_slug", "region", "app_type", "user_id", "allowed_origins")
values
($1, $2, $3, $4, $5)
RETURNING id, app_slug, region, app_type, user_id, allowed_origins
`

type App_InsertParams struct {
	AppSlug        string      `json:"app_slug"`
	Regions        []Region    `json:"regions"`
	AppType        AppType     `json:"app_type"`
	UserID         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

func (q *Queries) App_Insert(ctx context.Context, arg App_InsertParams) (App, error) {
	row := q.db.QueryRow(ctx, app_Insert,
		arg.AppSlug,
		arg.Regions,
		arg.AppType,
		arg.UserID,
		arg.AllowedOrigins,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserID,
		&i.AllowedOrigins,
	)
	return i, err
}

const app_Key_Insert = `-- name: App_Key_Insert :one
INSERT INTO "app_api_key"
("app_id", "id", "name", "prefix", "suffix")
VALUES
($1, $2, $3, $4, $5)
RETURNING id, app_id, created_at, updated_at, name, prefix, suffix, expires_at
`

type App_Key_InsertParams struct {
	AppID  pgtype.UUID `json:"app_id"`
	ID     string      `json:"id"`
	Name   pgtype.Text `json:"name"`
	Prefix pgtype.Text `json:"prefix"`
	Suffix pgtype.Text `json:"suffix"`
}

func (q *Queries) App_Key_Insert(ctx context.Context, arg App_Key_InsertParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, app_Key_Insert,
		arg.AppID,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.Suffix,
	)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Prefix,
		&i.Suffix,
		&i.ExpiresAt,
	)
	return i, err
}

const credential_Insert = `-- name: Credential_Insert :one
INSERT INTO "credential" ("token", "user_id", "app_id", "channel_id", "type", "permissions", "expires_at")
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token, user_id, app_id, channel_id, type, permissions, expires_at, created_at
`

type Credential_InsertParams struct {
	Token       string           `json:"token"`
	UserID      pgtype.UUID      `json:"user_id"`
	AppID       pgtype.UUID      `json:"app_id"`
	ChannelID   pgtype.Text      `json:"channel_id"`
	Type        CredentialType   `json:"type"`
	Permissions string           `json:"permissions"`
	ExpiresAt   pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) Credential_Insert(ctx context.Context, arg Credential_InsertParams) (Credential, error) {
	row := q.db.QueryRow(ctx, credential_Insert,
		arg.Token,
		arg.UserID,
		arg.AppID,
		arg.ChannelID,
		arg.Type,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.AppID,
		&i.ChannelID,
		&i.Type,
		&i.Permissions,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const userEmail_Insert = `-- name: UserEmail_Insert :one
INSERT INTO "user_email"
("email", "user_id", "code")
VALUES($1, $2, $3)
RETURNING id, email, user_id, created_at, updated_at, verified_at, code
`

type UserEmail_InsertParams struct {
	Email  string      `json:"email"`
	UserID pgtype.UUID `json:"user_id"`
	Code   string      `json:"code"`
}

func (q *Queries) UserEmail_Insert(ctx context.Context, arg UserEmail_InsertParams) (UserEmail, error) {
	row := q.db.QueryRow(ctx, userEmail_Insert, arg.Email, arg.UserID, arg.Code)
	var i UserEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.Code,
	)
	return i, err
}

const user_Insert = `-- name: User_Insert :one
insert into "user"("hash") values($1) RETURNING id, hash, created_at, updated_at, role, number_of_emails
`

func (q *Queries) User_Insert(ctx context.Context, hash string) (User, error) {
	row := q.db.QueryRow(ctx, user_Insert, hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.NumberOfEmails,
	)
	return i, err
}
