// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Key_List = `-- name: App_Key_List :many
SELECT id, app_id, created_at, updated_at, key, name from "app_api_key"
WHERE   "app_id" = $1
Limit 20
OFFSET 10 *  $2::int
`

type App_Key_ListParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	PageIdx int32       `json:"page_idx"`
}

func (q *Queries) App_Key_List(ctx context.Context, arg App_Key_ListParams) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, app_Key_List, arg.AppID, arg.PageIdx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppApiKey
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Key,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userEmails_List_ByUserID = `-- name: UserEmails_List_ByUserID :many
SELECT
    id, email, user_id, created_at, updated_at, verified_at, code
FROM "user_email"
WHERE "user_id" = $1
ORDER BY created_at DESC
`

func (q *Queries) UserEmails_List_ByUserID(ctx context.Context, userID pgtype.UUID) ([]UserEmail, error) {
	rows, err := q.db.Query(ctx, userEmails_List_ByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEmail
	for rows.Next() {
		var i UserEmail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedAt,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
