// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppType string

const (
	AppTypeFree     AppType = "free"
	AppTypeStandard AppType = "standard"
	AppTypePro      AppType = "pro"
)

func (e *AppType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppType(s)
	case string:
		*e = AppType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppType: %T", src)
	}
	return nil
}

type NullAppType struct {
	AppType AppType `json:"app_type"`
	Valid   bool    `json:"valid"` // Valid is true if AppType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppType) Scan(value interface{}) error {
	if value == nil {
		ns.AppType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppType), nil
}

func (e AppType) Valid() bool {
	switch e {
	case AppTypeFree,
		AppTypeStandard,
		AppTypePro:
		return true
	}
	return false
}

func AllAppTypeValues() []AppType {
	return []AppType{
		AppTypeFree,
		AppTypeStandard,
		AppTypePro,
	}
}

type Operation string

const (
	OperationCREATE  Operation = "CREATE"
	OperationREAD    Operation = "READ"
	OperationDESTROY Operation = "DESTROY"
	OperationUPDATE  Operation = "UPDATE"
)

func (e *Operation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Operation(s)
	case string:
		*e = Operation(s)
	default:
		return fmt.Errorf("unsupported scan type for Operation: %T", src)
	}
	return nil
}

type NullOperation struct {
	Operation Operation `json:"operation"`
	Valid     bool      `json:"valid"` // Valid is true if Operation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperation) Scan(value interface{}) error {
	if value == nil {
		ns.Operation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Operation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Operation), nil
}

func (e Operation) Valid() bool {
	switch e {
	case OperationCREATE,
		OperationREAD,
		OperationDESTROY,
		OperationUPDATE:
		return true
	}
	return false
}

func AllOperationValues() []Operation {
	return []Operation{
		OperationCREATE,
		OperationREAD,
		OperationDESTROY,
		OperationUPDATE,
	}
}

type Region string

const (
	RegionDk1 Region = "dk1"
)

func (e *Region) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Region(s)
	case string:
		*e = Region(s)
	default:
		return fmt.Errorf("unsupported scan type for Region: %T", src)
	}
	return nil
}

type NullRegion struct {
	Region Region `json:"region"`
	Valid  bool   `json:"valid"` // Valid is true if Region is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegion) Scan(value interface{}) error {
	if value == nil {
		ns.Region, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Region.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Region), nil
}

func (e Region) Valid() bool {
	switch e {
	case RegionDk1:
		return true
	}
	return false
}

func AllRegionValues() []Region {
	return []Region{
		RegionDk1,
	}
}

type Resource string

const (
	ResourceAPP Resource = "APP"
	ResourceKEY Resource = "KEY"
	ResourceOTT Resource = "OTT"
)

func (e *Resource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Resource(s)
	case string:
		*e = Resource(s)
	default:
		return fmt.Errorf("unsupported scan type for Resource: %T", src)
	}
	return nil
}

type NullResource struct {
	Resource Resource `json:"resource"`
	Valid    bool     `json:"valid"` // Valid is true if Resource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResource) Scan(value interface{}) error {
	if value == nil {
		ns.Resource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Resource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Resource), nil
}

func (e Resource) Valid() bool {
	switch e {
	case ResourceAPP,
		ResourceKEY,
		ResourceOTT:
		return true
	}
	return false
}

func AllResourceValues() []Resource {
	return []Resource{
		ResourceAPP,
		ResourceKEY,
		ResourceOTT,
	}
}

type UserRole string

const (
	UserRoleSuper UserRole = "super"
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleSuper,
		UserRoleAdmin,
		UserRoleUser:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleSuper,
		UserRoleAdmin,
		UserRoleUser,
	}
}

type App struct {
	ID             pgtype.UUID `json:"id"`
	AppSlug        string      `json:"app_slug"`
	Region         []Region    `json:"region"`
	AppType        AppType     `json:"app_type"`
	UserID         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

type AppApiKey struct {
	ID        pgtype.UUID      `json:"id"`
	AppID     pgtype.UUID      `json:"app_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Key       pgtype.Text      `json:"key"`
	Name      pgtype.Text      `json:"name"`
}

type User struct {
	ID             pgtype.UUID      `json:"id"`
	Hash           string           `json:"hash"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Role           NullUserRole     `json:"role"`
	NumberOfEmails int32            `json:"number_of_emails"`
}

type UserEmail struct {
	ID         pgtype.UUID      `json:"id"`
	Email      string           `json:"email"`
	UserID     pgtype.UUID      `json:"user_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	VerifiedAt pgtype.Timestamp `json:"verified_at"`
	Code       string           `json:"code"`
}
