// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password.update.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const user_Password_Update = `-- name: User_Password_Update :exec
UPDATE "user"
SET "hash" = $1
Where "id" =  $2
`

type User_Password_UpdateParams struct {
	Hash   string      `json:"hash"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) User_Password_Update(ctx context.Context, arg User_Password_UpdateParams) error {
	_, err := q.db.Exec(ctx, user_Password_Update, arg.Hash, arg.UserID)
	return err
}
