// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select-by-code.sql

package repository

import (
	"context"
)

const userEmail_SelectByCode = `-- name: UserEmail_SelectByCode :one
SELECT id, email, user_id, created_at, updated_at, verified_at, code
FROM "user_email"
WHERE "code" = $1
LIMIT 1
`

func (q *Queries) UserEmail_SelectByCode(ctx context.Context, code string) (UserEmail, error) {
	row := q.db.QueryRow(ctx, userEmail_SelectByCode, code)
	var i UserEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.Code,
	)
	return i, err
}
