// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: select.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Key_Select = `-- name: App_Key_Select :one
SELECT id, app_id, created_at, updated_at, name, prefix, suffix, expires_at
FROM "app_api_key"
WHERE "id" = $1 AND "app_id" = $2
limit 1
`

type App_Key_SelectParams struct {
	Key   string      `json:"key"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) App_Key_Select(ctx context.Context, arg App_Key_SelectParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, app_Key_Select, arg.Key, arg.AppID)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Prefix,
		&i.Suffix,
		&i.ExpiresAt,
	)
	return i, err
}

const app_Select = `-- name: App_Select :one
SELECT id, app_slug, region, app_type, user_id, allowed_origins from "app"
where "id" = $1
limit 1
`

func (q *Queries) App_Select(ctx context.Context, appID pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, app_Select, appID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserID,
		&i.AllowedOrigins,
	)
	return i, err
}

const credential_SelectByToken = `-- name: Credential_SelectByToken :one
SELECT id, token, user_id, app_id, channel_id, type, permissions, expires_at, created_at FROM "credential"
WHERE "token" = $1
LIMIT 1
`

func (q *Queries) Credential_SelectByToken(ctx context.Context, token string) (Credential, error) {
	row := q.db.QueryRow(ctx, credential_SelectByToken, token)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.AppID,
		&i.ChannelID,
		&i.Type,
		&i.Permissions,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const user_Select = `-- name: User_Select :one
SELECT id, hash, created_at, updated_at, role, number_of_emails FROM "user"
WHERE "id" = $1
LIMIT 1
`

func (q *Queries) User_Select(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, user_Select, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.NumberOfEmails,
	)
	return i, err
}
