// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const app_Update = `-- name: App_Update :one
UPDATE "app"
SET
    "app_slug" = $1,
    "allowed_origins" = $2,
    "app_type" = $3
WHERE "id" = $4
RETURNING id, app_slug, region, app_type, user_id, allowed_origins
`

type App_UpdateParams struct {
	AppSlug        string      `json:"app_slug"`
	AllowedOrigins []string    `json:"allowed_origins"`
	AppType        AppType     `json:"app_type"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) App_Update(ctx context.Context, arg App_UpdateParams) (App, error) {
	row := q.db.QueryRow(ctx, app_Update,
		arg.AppSlug,
		arg.AllowedOrigins,
		arg.AppType,
		arg.ID,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserID,
		&i.AllowedOrigins,
	)
	return i, err
}
