// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create-app.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertApp = `-- name: InsertApp :one

INSERT INTO "app"
("appSlug", "region", "appType", "userId", "allowedOrigins")
values
($1, $2, $3, $4, allowedOrigins)
RETURNING id, "appSlug", region, "appType", "userId", "allowedOrigins"
`

type InsertAppParams struct {
	Appslug string      `json:"appslug"`
	Region  []Region    `json:"region"`
	Apptype AppType     `json:"apptype"`
	Userid  pgtype.UUID `json:"userid"`
}

// "id" UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
// "app_slug" VARCHAR(255) NOT NULL UNIQUE,
// "region" region[] NOT NULL,
// "app_type" app_type NOT NULL
func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) (App, error) {
	row := q.db.QueryRow(ctx, insertApp,
		arg.Appslug,
		arg.Region,
		arg.Apptype,
		arg.Userid,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.AppSlug,
		&i.Region,
		&i.AppType,
		&i.UserId,
		&i.AllowedOrigins,
	)
	return i, err
}
