// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppType string

const (
	AppTypeFree     AppType = "free"
	AppTypeStandard AppType = "standard"
	AppTypePro      AppType = "pro"
)

func (e *AppType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppType(s)
	case string:
		*e = AppType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppType: %T", src)
	}
	return nil
}

type NullAppType struct {
	AppType AppType `json:"app_type"`
	Valid   bool    `json:"valid"` // Valid is true if AppType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppType) Scan(value interface{}) error {
	if value == nil {
		ns.AppType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppType), nil
}

func (e AppType) Valid() bool {
	switch e {
	case AppTypeFree,
		AppTypeStandard,
		AppTypePro:
		return true
	}
	return false
}

// AllAppTypeValues returns a slice of all defined AppType constants.
func AllAppTypeValues() []AppType {
	return []AppType{
		AppTypeFree,
		AppTypeStandard,
		AppTypePro,
	}
}

type Changeoperation string

const (
	ChangeoperationINSERT Changeoperation = "INSERT"
	ChangeoperationDELETE Changeoperation = "DELETE"
	ChangeoperationUPDATE Changeoperation = "UPDATE"
)

func (e *Changeoperation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Changeoperation(s)
	case string:
		*e = Changeoperation(s)
	default:
		return fmt.Errorf("unsupported scan type for Changeoperation: %T", src)
	}
	return nil
}

type NullChangeoperation struct {
	Changeoperation Changeoperation `json:"changeoperation"`
	Valid           bool            `json:"valid"` // Valid is true if Changeoperation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChangeoperation) Scan(value interface{}) error {
	if value == nil {
		ns.Changeoperation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Changeoperation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChangeoperation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Changeoperation), nil
}

func (e Changeoperation) Valid() bool {
	switch e {
	case ChangeoperationINSERT,
		ChangeoperationDELETE,
		ChangeoperationUPDATE:
		return true
	}
	return false
}

// AllChangeoperationValues returns a slice of all defined Changeoperation constants.
func AllChangeoperationValues() []Changeoperation {
	return []Changeoperation{
		ChangeoperationINSERT,
		ChangeoperationDELETE,
		ChangeoperationUPDATE,
	}
}

type Region string

const (
	RegionDk1 Region = "dk1"
)

func (e *Region) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Region(s)
	case string:
		*e = Region(s)
	default:
		return fmt.Errorf("unsupported scan type for Region: %T", src)
	}
	return nil
}

type NullRegion struct {
	Region Region `json:"region"`
	Valid  bool   `json:"valid"` // Valid is true if Region is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegion) Scan(value interface{}) error {
	if value == nil {
		ns.Region, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Region.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegion) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Region), nil
}

func (e Region) Valid() bool {
	switch e {
	case RegionDk1:
		return true
	}
	return false
}

// AllRegionValues returns a slice containing every defined Region constant.
func AllRegionValues() []Region {
	return []Region{
		RegionDk1,
	}
}

type App struct {
	ID             pgtype.UUID `json:"id"`
	AppSlug        string      `json:"app_slug"`
	Region         []Region    `json:"region"`
	AppType        AppType     `json:"app_type"`
	UserId         pgtype.UUID `json:"user_id"`
	AllowedOrigins []string    `json:"allowed_origins"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	Hash      string           `json:"hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type UserHistory struct {
	ID        pgtype.UUID      `json:"id"`
	UserId    pgtype.UUID      `json:"user_id"`
	Email     string           `json:"email"`
	Hash      string           `json:"hash"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	ChangedAt pgtype.Timestamp `json:"changed_at"`
	ChangedBy pgtype.UUID      `json:"changed_by"`
	Operation Changeoperation  `json:"operation"`
}