// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update-password.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE "user"
SET "hash" = $1
Where "id" =  $2
`

type UpdateUserPasswordParams struct {
	Hash   string      `json:"hash"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Hash, arg.UserID)
	return err
}
