// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update-email.sql

package repository

import (
	"context"
)

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE "user"
SET "email" = $1
Where "id" $2
`

type UpdateUserEmailParams struct {
	Email  string      `json:"email"`
	UserID interface{} `json:"user_id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.UserID)
	return err
}
